net: igc: use ethtool_puts()
One of the memcpy calls deferences an array when it should not, causing
the following error with W=1

In file included from drivers/net/ethernet/intel/igc/igc_ethtool.c:5:
In file included from ./include/linux/if_vlan.h:10:
In file included from ./include/linux/netdevice.h:24:
In file included from ./include/linux/timer.h:8:
In file included from ./include/linux/debugobjects.h:6:
In file included from ./include/linux/spinlock.h:56:
In file included from ./include/linux/preempt.h:79:
In file included from ./arch/powerpc/include/asm/preempt.h:5:
In file included from ./include/asm-generic/preempt.h:5:
In file included from ./include/linux/thread_info.h:23:
In file included from ./arch/powerpc/include/asm/current.h:13:
In file included from ./arch/powerpc/include/asm/paca.h:16:
In file included from ./include/linux/string.h:386:
./include/linux/fortify-string.h:578:4: error: call to
'__read_overflow2_field' declared with 'warning' attribute: detected read
beyond size of field (2nd parameter); maybe use
      struct_group()? [-Werror,-Wattribute-warning]
  578 |                         __read_overflow2_field(q_size_field, size);
      |                         ^
1 error generated.

Change both memcpy calls to use ethtool_puts(), which is the modern
type safe way to copy ethtool gstrings.

Signed-off-by: Rosen Penev <rosenp@gmail.com>