agp/uninorth: remove unused variable
size is assigned but never read. Remove the variable and its dead
assignment to fix the clang build warning:

  drivers/char/agp/uninorth-agp.c:373:6: error: variable 'size' set
  but not used [-Werror,-Wunused-but-set-variable]

Assisted-by: opencode:big-pickle
Signed-off-by: Rosen Penev <rosenp@gmail.com>