video/riva: remove unused variable in nv4CalcArbitration
pclks is assigned but never read in nv4CalcArbitration. Remove the
variable and its dead assignments to fix the clang build warning:

  drivers/video/fbdev/riva/riva_hw.c:662:24: error: variable 'pclks'
  set but not used [-Werror,-Wunused-but-set-variable]

Assisted-by: opencode:big-pickle
Signed-off-by: Rosen Penev <rosenp@gmail.com>